package com.abhiiterates.os.assessment.service;

import com.abhiiterates.os.assessment.domain.QuestionDifficulty;
import com.abhiiterates.os.assessment.domain.QuestionType;
import com.abhiiterates.os.assessment.dto.GeneratedQuestionDto;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;

import java.util.ArrayList;
import java.util.List;

@Service
@Slf4j
public class AssessmentValidationEngineImpl implements AssessmentValidationEngine {

    @Override
    public List<GeneratedQuestionDto> validateAndSanitize(List<GeneratedQuestionDto> questions) {
        if (questions == null || questions.isEmpty()) {
            throw new IllegalArgumentException("Generated question list is empty or null.");
        }

        List<GeneratedQuestionDto> validQuestions = new ArrayList<>();

        for (int i = 0; i < questions.size(); i++) {
            GeneratedQuestionDto q = questions.get(i);
            if (q.getQuestionText() == null || q.getQuestionText().isBlank()) {
                log.warn("Skipping question index {} due to missing question text.", i);
                continue;
            }

            if (q.getOptions() == null || q.getOptions().size() < 2) {
                log.warn("Skipping question [{}] due to fewer than 2 options.", q.getQuestionText());
                continue;
            }

            boolean hasCorrect = q.getOptions().stream().anyMatch(opt -> Boolean.TRUE.equals(opt.getIsCorrect()));
            if (!hasCorrect) {
                log.warn("Question [{}] had no correct option marked. Marking first option as correct.", q.getQuestionText());
                q.getOptions().get(0).setIsCorrect(true);
            }

            if (q.getQuestionType() == null) {
                q.setQuestionType(QuestionType.MULTIPLE_CHOICE);
            }
            if (q.getDifficulty() == null) {
                q.setDifficulty(QuestionDifficulty.MEDIUM);
            }
            if (q.getMarks() == null || q.getMarks() <= 0) {
                q.setMarks(1.0);
            }

            validQuestions.add(q);
        }

        if (validQuestions.isEmpty()) {
            throw new IllegalStateException("Failed to validate any questions generated by AI.");
        }

        log.info("Validated and sanitized {} out of {} generated questions.", validQuestions.size(), questions.size());
        return validQuestions;
    }
}
